// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package post_model_collect

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PostModelPredictClient is the client API for PostModelPredict service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PostModelPredictClient interface {
	CollectPostDeal(ctx context.Context, in *CollectPostDealRequest, opts ...grpc.CallOption) (*CollectPostDealResponse, error)
}

type postModelPredictClient struct {
	cc grpc.ClientConnInterface
}

func NewPostModelPredictClient(cc grpc.ClientConnInterface) PostModelPredictClient {
	return &postModelPredictClient{cc}
}

func (c *postModelPredictClient) CollectPostDeal(ctx context.Context, in *CollectPostDealRequest, opts ...grpc.CallOption) (*CollectPostDealResponse, error) {
	out := new(CollectPostDealResponse)
	err := c.cc.Invoke(ctx, "/post_data_collect.PostModelPredict/CollectPostDeal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostModelPredictServer is the server API for PostModelPredict service.
// All implementations must embed UnimplementedPostModelPredictServer
// for forward compatibility
type PostModelPredictServer interface {
	CollectPostDeal(context.Context, *CollectPostDealRequest) (*CollectPostDealResponse, error)
	mustEmbedUnimplementedPostModelPredictServer()
}

// UnimplementedPostModelPredictServer must be embedded to have forward compatible implementations.
type UnimplementedPostModelPredictServer struct {
}

func (UnimplementedPostModelPredictServer) CollectPostDeal(context.Context, *CollectPostDealRequest) (*CollectPostDealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectPostDeal not implemented")
}
func (UnimplementedPostModelPredictServer) mustEmbedUnimplementedPostModelPredictServer() {}

// UnsafePostModelPredictServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostModelPredictServer will
// result in compilation errors.
type UnsafePostModelPredictServer interface {
	mustEmbedUnimplementedPostModelPredictServer()
}

func RegisterPostModelPredictServer(s grpc.ServiceRegistrar, srv PostModelPredictServer) {
	s.RegisterService(&PostModelPredict_ServiceDesc, srv)
}

func _PostModelPredict_CollectPostDeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectPostDealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostModelPredictServer).CollectPostDeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post_data_collect.PostModelPredict/CollectPostDeal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostModelPredictServer).CollectPostDeal(ctx, req.(*CollectPostDealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PostModelPredict_ServiceDesc is the grpc.ServiceDesc for PostModelPredict service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostModelPredict_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "post_data_collect.PostModelPredict",
	HandlerType: (*PostModelPredictServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CollectPostDeal",
			Handler:    _PostModelPredict_CollectPostDeal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "post_data_collect.proto",
}
