// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: post_data_manage.proto

package post_data_manage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeneratePostPredictDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag string `protobuf:"bytes,1,opt,name=Tag,proto3" json:"Tag,omitempty"`
}

func (x *GeneratePostPredictDataRequest) Reset() {
	*x = GeneratePostPredictDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_post_data_manage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneratePostPredictDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePostPredictDataRequest) ProtoMessage() {}

func (x *GeneratePostPredictDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_data_manage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePostPredictDataRequest.ProtoReflect.Descriptor instead.
func (*GeneratePostPredictDataRequest) Descriptor() ([]byte, []int) {
	return file_post_data_manage_proto_rawDescGZIP(), []int{0}
}

func (x *GeneratePostPredictDataRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type GeneratePostPredictDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Status  int32  `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	TaskId  string `protobuf:"bytes,3,opt,name=TaskId,proto3" json:"TaskId,omitempty"`
}

func (x *GeneratePostPredictDataResponse) Reset() {
	*x = GeneratePostPredictDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_post_data_manage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneratePostPredictDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePostPredictDataResponse) ProtoMessage() {}

func (x *GeneratePostPredictDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_data_manage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePostPredictDataResponse.ProtoReflect.Descriptor instead.
func (*GeneratePostPredictDataResponse) Descriptor() ([]byte, []int) {
	return file_post_data_manage_proto_rawDescGZIP(), []int{1}
}

func (x *GeneratePostPredictDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GeneratePostPredictDataResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GeneratePostPredictDataResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetPostPredictTaskStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string `protobuf:"bytes,1,opt,name=TaskId,proto3" json:"TaskId,omitempty"`
}

func (x *GetPostPredictTaskStatusRequest) Reset() {
	*x = GetPostPredictTaskStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_post_data_manage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPostPredictTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostPredictTaskStatusRequest) ProtoMessage() {}

func (x *GetPostPredictTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_data_manage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostPredictTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPostPredictTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_post_data_manage_proto_rawDescGZIP(), []int{2}
}

func (x *GetPostPredictTaskStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type PredictTaskStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message  string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Status   int32  `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	Finished bool   `protobuf:"varint,3,opt,name=Finished,proto3" json:"Finished,omitempty"`
}

func (x *PredictTaskStatus) Reset() {
	*x = PredictTaskStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_post_data_manage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredictTaskStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictTaskStatus) ProtoMessage() {}

func (x *PredictTaskStatus) ProtoReflect() protoreflect.Message {
	mi := &file_post_data_manage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictTaskStatus.ProtoReflect.Descriptor instead.
func (*PredictTaskStatus) Descriptor() ([]byte, []int) {
	return file_post_data_manage_proto_rawDescGZIP(), []int{3}
}

func (x *PredictTaskStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PredictTaskStatus) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PredictTaskStatus) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

type GetPostPredictTaskStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message           string             `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Status            int32              `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	PredictTaskStatus *PredictTaskStatus `protobuf:"bytes,3,opt,name=PredictTaskStatus,proto3" json:"PredictTaskStatus,omitempty"`
}

func (x *GetPostPredictTaskStatusResponse) Reset() {
	*x = GetPostPredictTaskStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_post_data_manage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPostPredictTaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostPredictTaskStatusResponse) ProtoMessage() {}

func (x *GetPostPredictTaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_data_manage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostPredictTaskStatusResponse.ProtoReflect.Descriptor instead.
func (*GetPostPredictTaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_post_data_manage_proto_rawDescGZIP(), []int{4}
}

func (x *GetPostPredictTaskStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetPostPredictTaskStatusResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetPostPredictTaskStatusResponse) GetPredictTaskStatus() *PredictTaskStatus {
	if x != nil {
		return x.PredictTaskStatus
	}
	return nil
}

type GetPostPredictDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageSize   int32  `protobuf:"varint,1,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	PageNum    int32  `protobuf:"varint,2,opt,name=PageNum,proto3" json:"PageNum,omitempty"`
	DealDate   string `protobuf:"bytes,3,opt,name=DealDate,proto3" json:"DealDate,omitempty"`
	DealRegion string `protobuf:"bytes,4,opt,name=DealRegion,proto3" json:"DealRegion,omitempty"`
}

func (x *GetPostPredictDataRequest) Reset() {
	*x = GetPostPredictDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_post_data_manage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPostPredictDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostPredictDataRequest) ProtoMessage() {}

func (x *GetPostPredictDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_data_manage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostPredictDataRequest.ProtoReflect.Descriptor instead.
func (*GetPostPredictDataRequest) Descriptor() ([]byte, []int) {
	return file_post_data_manage_proto_rawDescGZIP(), []int{5}
}

func (x *GetPostPredictDataRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetPostPredictDataRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetPostPredictDataRequest) GetDealDate() string {
	if x != nil {
		return x.DealDate
	}
	return ""
}

func (x *GetPostPredictDataRequest) GetDealRegion() string {
	if x != nil {
		return x.DealRegion
	}
	return ""
}

type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Features []float64 `protobuf:"fixed64,1,rep,packed,name=features,proto3" json:"features,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_post_data_manage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_post_data_manage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_post_data_manage_proto_rawDescGZIP(), []int{6}
}

func (x *Point) GetFeatures() []float64 {
	if x != nil {
		return x.Features
	}
	return nil
}

type PredictDeal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Points   []*Point `protobuf:"bytes,1,rep,name=Points,proto3" json:"Points,omitempty"`
	Order    []int32  `protobuf:"varint,2,rep,packed,name=Order,proto3" json:"Order,omitempty"`
	Start    int32    `protobuf:"varint,3,opt,name=Start,proto3" json:"Start,omitempty"`
	Length   int32    `protobuf:"varint,4,opt,name=Length,proto3" json:"Length,omitempty"`
	Region   string   `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	DealDate string   `protobuf:"bytes,6,opt,name=deal_date,json=dealDate,proto3" json:"deal_date,omitempty"`
}

func (x *PredictDeal) Reset() {
	*x = PredictDeal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_post_data_manage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredictDeal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictDeal) ProtoMessage() {}

func (x *PredictDeal) ProtoReflect() protoreflect.Message {
	mi := &file_post_data_manage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictDeal.ProtoReflect.Descriptor instead.
func (*PredictDeal) Descriptor() ([]byte, []int) {
	return file_post_data_manage_proto_rawDescGZIP(), []int{7}
}

func (x *PredictDeal) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *PredictDeal) GetOrder() []int32 {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *PredictDeal) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *PredictDeal) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *PredictDeal) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *PredictDeal) GetDealDate() string {
	if x != nil {
		return x.DealDate
	}
	return ""
}

type PostPredictData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PredictDeals []*PredictDeal `protobuf:"bytes,1,rep,name=PredictDeals,proto3" json:"PredictDeals,omitempty"` // int32 total = 2;
}

func (x *PostPredictData) Reset() {
	*x = PostPredictData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_post_data_manage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostPredictData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostPredictData) ProtoMessage() {}

func (x *PostPredictData) ProtoReflect() protoreflect.Message {
	mi := &file_post_data_manage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostPredictData.ProtoReflect.Descriptor instead.
func (*PostPredictData) Descriptor() ([]byte, []int) {
	return file_post_data_manage_proto_rawDescGZIP(), []int{8}
}

func (x *PostPredictData) GetPredictDeals() []*PredictDeal {
	if x != nil {
		return x.PredictDeals
	}
	return nil
}

type GetPostPredictDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message         string           `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Status          int32            `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	PostPredictData *PostPredictData `protobuf:"bytes,3,opt,name=PostPredictData,proto3" json:"PostPredictData,omitempty"`
}

func (x *GetPostPredictDataResponse) Reset() {
	*x = GetPostPredictDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_post_data_manage_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPostPredictDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostPredictDataResponse) ProtoMessage() {}

func (x *GetPostPredictDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_data_manage_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostPredictDataResponse.ProtoReflect.Descriptor instead.
func (*GetPostPredictDataResponse) Descriptor() ([]byte, []int) {
	return file_post_data_manage_proto_rawDescGZIP(), []int{9}
}

func (x *GetPostPredictDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetPostPredictDataResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetPostPredictDataResponse) GetPostPredictData() *PostPredictData {
	if x != nil {
		return x.PostPredictData
	}
	return nil
}

var File_post_data_manage_proto protoreflect.FileDescriptor

var file_post_data_manage_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x22, 0x32, 0x0a, 0x1e, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x54, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x54, 0x61, 0x67, 0x22, 0x6b,
	0x0a, 0x1f, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x50, 0x72,
	0x65, 0x64, 0x69, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x39, 0x0a, 0x1f, 0x47,
	0x65, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x54, 0x61, 0x73,
	0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x54, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x61, 0x0a, 0x11, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63,
	0x74, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x22, 0xa7, 0x01, 0x0a, 0x20, 0x47, 0x65,
	0x74, 0x50, 0x6f, 0x73, 0x74, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x54, 0x61, 0x73, 0x6b,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x51, 0x0a, 0x11, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x6f,
	0x73, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x50,
	0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x11, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x8d, 0x01, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x50,
	0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x50, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x50, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x65, 0x61, 0x6c, 0x44,
	0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x65, 0x61, 0x6c, 0x44,
	0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x44, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x22, 0x23, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x08,
	0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0xb7, 0x01, 0x0a, 0x0b, 0x50, 0x72, 0x65,
	0x64, 0x69, 0x63, 0x74, 0x44, 0x65, 0x61, 0x6c, 0x12, 0x2f, 0x0a, 0x06, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x52, 0x06, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x61, 0x6c, 0x5f, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x61, 0x6c, 0x44, 0x61,
	0x74, 0x65, 0x22, 0x54, 0x0a, 0x0f, 0x50, 0x6f, 0x73, 0x74, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x41, 0x0a, 0x0c, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74,
	0x44, 0x65, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x6f,
	0x73, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x50,
	0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x44, 0x65, 0x61, 0x6c, 0x52, 0x0c, 0x50, 0x72, 0x65, 0x64,
	0x69, 0x63, 0x74, 0x44, 0x65, 0x61, 0x6c, 0x73, 0x22, 0x9b, 0x01, 0x0a, 0x1a, 0x47, 0x65, 0x74,
	0x50, 0x6f, 0x73, 0x74, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x4b, 0x0a, 0x0f, 0x50, 0x6f, 0x73,
	0x74, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0f, 0x50, 0x6f, 0x73, 0x74, 0x50, 0x72, 0x65, 0x64, 0x69,
	0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x32, 0x86, 0x02, 0x0a, 0x0e, 0x50, 0x6f, 0x73, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x12, 0x80, 0x01, 0x0a, 0x17, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x30, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x50, 0x6f, 0x73, 0x74, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x71, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x2b, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x50, 0x72, 0x65,
	0x64, 0x69, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2c, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x13, 0x5a, 0x11, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_post_data_manage_proto_rawDescOnce sync.Once
	file_post_data_manage_proto_rawDescData = file_post_data_manage_proto_rawDesc
)

func file_post_data_manage_proto_rawDescGZIP() []byte {
	file_post_data_manage_proto_rawDescOnce.Do(func() {
		file_post_data_manage_proto_rawDescData = protoimpl.X.CompressGZIP(file_post_data_manage_proto_rawDescData)
	})
	return file_post_data_manage_proto_rawDescData
}

var file_post_data_manage_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_post_data_manage_proto_goTypes = []interface{}{
	(*GeneratePostPredictDataRequest)(nil),   // 0: post_data_manage.GeneratePostPredictDataRequest
	(*GeneratePostPredictDataResponse)(nil),  // 1: post_data_manage.GeneratePostPredictDataResponse
	(*GetPostPredictTaskStatusRequest)(nil),  // 2: post_data_manage.GetPostPredictTaskStatusRequest
	(*PredictTaskStatus)(nil),                // 3: post_data_manage.PredictTaskStatus
	(*GetPostPredictTaskStatusResponse)(nil), // 4: post_data_manage.GetPostPredictTaskStatusResponse
	(*GetPostPredictDataRequest)(nil),        // 5: post_data_manage.GetPostPredictDataRequest
	(*Point)(nil),                            // 6: post_data_manage.Point
	(*PredictDeal)(nil),                      // 7: post_data_manage.PredictDeal
	(*PostPredictData)(nil),                  // 8: post_data_manage.PostPredictData
	(*GetPostPredictDataResponse)(nil),       // 9: post_data_manage.GetPostPredictDataResponse
}
var file_post_data_manage_proto_depIdxs = []int32{
	3, // 0: post_data_manage.GetPostPredictTaskStatusResponse.PredictTaskStatus:type_name -> post_data_manage.PredictTaskStatus
	6, // 1: post_data_manage.PredictDeal.Points:type_name -> post_data_manage.Point
	7, // 2: post_data_manage.PostPredictData.PredictDeals:type_name -> post_data_manage.PredictDeal
	8, // 3: post_data_manage.GetPostPredictDataResponse.PostPredictData:type_name -> post_data_manage.PostPredictData
	0, // 4: post_data_manage.PostDataManage.GeneratePostPredictData:input_type -> post_data_manage.GeneratePostPredictDataRequest
	5, // 5: post_data_manage.PostDataManage.GetPostPredictData:input_type -> post_data_manage.GetPostPredictDataRequest
	1, // 6: post_data_manage.PostDataManage.GeneratePostPredictData:output_type -> post_data_manage.GeneratePostPredictDataResponse
	9, // 7: post_data_manage.PostDataManage.GetPostPredictData:output_type -> post_data_manage.GetPostPredictDataResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_post_data_manage_proto_init() }
func file_post_data_manage_proto_init() {
	if File_post_data_manage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_post_data_manage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneratePostPredictDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_post_data_manage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneratePostPredictDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_post_data_manage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPostPredictTaskStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_post_data_manage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PredictTaskStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_post_data_manage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPostPredictTaskStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_post_data_manage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPostPredictDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_post_data_manage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_post_data_manage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PredictDeal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_post_data_manage_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostPredictData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_post_data_manage_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPostPredictDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_post_data_manage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_post_data_manage_proto_goTypes,
		DependencyIndexes: file_post_data_manage_proto_depIdxs,
		MessageInfos:      file_post_data_manage_proto_msgTypes,
	}.Build()
	File_post_data_manage_proto = out.File
	file_post_data_manage_proto_rawDesc = nil
	file_post_data_manage_proto_goTypes = nil
	file_post_data_manage_proto_depIdxs = nil
}
