// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package post_model_manage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PostModelManageClient is the client API for PostModelManage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PostModelManageClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type postModelManageClient struct {
	cc grpc.ClientConnInterface
}

func NewPostModelManageClient(cc grpc.ClientConnInterface) PostModelManageClient {
	return &postModelManageClient{cc}
}

func (c *postModelManageClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/post_model_manage.PostModelManage/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostModelManageServer is the server API for PostModelManage service.
// All implementations must embed UnimplementedPostModelManageServer
// for forward compatibility
type PostModelManageServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedPostModelManageServer()
}

// UnimplementedPostModelManageServer must be embedded to have forward compatible implementations.
type UnimplementedPostModelManageServer struct {
}

func (UnimplementedPostModelManageServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedPostModelManageServer) mustEmbedUnimplementedPostModelManageServer() {}

// UnsafePostModelManageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostModelManageServer will
// result in compilation errors.
type UnsafePostModelManageServer interface {
	mustEmbedUnimplementedPostModelManageServer()
}

func RegisterPostModelManageServer(s grpc.ServiceRegistrar, srv PostModelManageServer) {
	s.RegisterService(&PostModelManage_ServiceDesc, srv)
}

func _PostModelManage_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostModelManageServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post_model_manage.PostModelManage/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostModelManageServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PostModelManage_ServiceDesc is the grpc.ServiceDesc for PostModelManage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostModelManage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "post_model_manage.PostModelManage",
	HandlerType: (*PostModelManageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _PostModelManage_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idl/post_model_manage.proto",
}
